### ISSUE TITLE
Лента избранного странно себя ведет, если добавлять и удалять самого себя

### ISSUE THREAD

**Issue by simoroshka** [GoodKitties/DiaryCommunity#14]
This: 
"Себя возможно добавить в избранное, при этом в ленте избранного своих записей не видишь, но строка под названием меняется на "удалить из избранного"
а если в избранном был один человек кроме тебя, то при удалении себя из избранного удаляется этот другой и собственный пост возникает в ленте"

**Comment by dkalinina** [comment]
Своих записей не видно было из-за вывода только первых 20 записей.
На примерно тех же действиях (тот же второй избранный) баг с появлением в ленте себя не воспроизвелся.
(картинка, подтверждающая, что он был)
![photo5206227441041909921](https://user-images.githubusercontent.com/14875152/32723936-5e857b6e-c880-11e7-92ae-de91d9e8d9f2.jpg)

**Comment by simoroshka** [comment]
что насчет второй части бага?

**Comment by ameliaailema** [comment]
вечер 13.11
в избранном мой дневник и еще один
- удалила себя. лента как была, так и осталась: мои и чужие посты
- обновила страницу, вижу только чужой дневник
- добавила себя, вижу все еще только чужой дневник
- обновила страницу, вижу снова и себя, и чужой дневник

**Comment by ameliaailema** [comment]
а вот если быть в избранном и удалить свой пост, то тебя редиректит к тебе в дневник, это возможно фича, но очень фрустрирует, особенно если в избранном было много постов,  а твой был только один, и после полной ленты ты удалив один пост попадаешь в визуально такую же, где постов нет
