### ISSUE TITLE
Не вмещается контент на главной странице

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/DiaryCommunity#21]
https://s8.hostingkartinok.com/uploads/images/2017/11/26d0bc10f48e60eeb2b695e4d85b8df1.png

**Comment by Neitent** [comment]
Не только главную. Ширина - большая проблема на телефона
https://hostingkartinok.com/show-image.php?id=9e8371ef3e4ba07d1f5472bcd3e46f84

**Comment by simoroshka** [comment]
31b6ce2eaf277488f23170c013338f6711dbb98e
