### ISSUE TITLE
Имеет значение регистр в e-mail

### ISSUE THREAD

**Issue by Neitent** [GoodKitties/DiaryCommunity#28]
При входе логиниться можно, только введя почту в прежнем регистре, Masha@mail.ru и masha@mail.ru - разные почты
И у меня получается зарегистрироваться еще раз на ту же почту в другом регистре. Neitent, neitent, neitenT - разные адреса почты.

PS: после нажатия на зарегистрироваться меня никуда не перебрасывает. Тоже не айс(

**Comment by bloodrizer** [comment]
+ и . тоже бы хорошо стрипнуть

**Comment by simoroshka** [comment]
(+) и (.) - валидные символы в имейлах
